version: '3.8'

services:
  web3-search:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ETH_RPC_URL=${ETH_RPC_URL:-https://sepolia.infura.io/v3/YOUR_PROJECT_ID}
      - PORT=8080
      - GIN_MODE=release
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 